### ISSUE TITLE
Fix deprecated dependencies

### ISSUE THREAD

**Issue by shinesanthosh** [shinesanthosh/react-todo#5]
Dependabot couldn't fix or bump some dependencies to newer versions. Please help to upgrade it

**Comment by marlonemmerich** [comment]
Hey! i create d [PR](https://github.com/shinesanthosh/react-todo/pull/6)
Can you check, please?

Now we have:
![image](https://user-images.githubusercontent.com/52637919/97787394-ac9ad180-1b90-11eb-82ed-111ee8d270a6.png)
Cya!

**Comment by shinesanthosh** [comment]
Thank you. Do I need to add any specific labels?

**Comment by marlonemmerich** [comment]
I'm here for the hacktoberfest but it's ok!
I completed the challenge
Thank you!

**Comment by shinesanthosh** [comment]
Hacktober fest is over
